/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnatomyHeatmap: typeof import('./src/components/AnatomyHeatmap.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CurrentWorkout: typeof import('./src/components/CurrentWorkout.vue')['default']
    ExistingWorkout: typeof import('./src/components/PreviousWorkouts.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PlannedWorkout: typeof import('./src/components/PlannedWorkout.vue')['default']
    PlanWorkout: typeof import('./src/components/PlanWorkout.vue')['default']
    PreviousWorkouts: typeof import('./src/components/PreviousWorkouts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkoutSummary: typeof import('./src/components/WorkoutSummary.vue')['default']
  }
}
